export const theme = {
    light: {
        background: '#f4f7fb',
        foreground: '#0f172a',
        card: '#ffffff',
        cardForeground: '#0f172a',
        popover: '#ffffff',
        popoverForeground: '#0f172a',
        primary: '#0f172a',
        primaryForeground: '#ffffff',
        secondary: '#eef2f7',
        secondaryForeground: '#1e293b',
        muted: '#edf2f7',
        mutedForeground: '#64748b',
        accent: '#edf2f7',
        accentForeground: '#1e293b',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        border: '#dbe3ee',
        input: '#d3dde8',
        inputBackground: '#f8fafc',
        ring: '#1e293b',
        radius: 14,
        chart1: '#ef6c57',
        chart2: '#2b9d8f',
        chart3: '#2563eb',
        chart4: '#d9b657',
        chart5: '#f39a4f',
    },
    dark: {
        background: '#09090b',
        foreground: '#fafafa',
        card: '#18181b', // Zinc-900
        cardForeground: '#fafafa',
        primary: '#fafafa',
        primaryForeground: '#18181b',
        secondary: '#27272a',
        secondaryForeground: '#fafafa',
        muted: '#27272a',
        mutedForeground: '#a1a1aa',
        accent: '#27272a',
        accentForeground: '#fafafa',
        destructive: '#7f1d1d',
        destructiveForeground: '#fecaca',
        border: '#27272a',
        input: '#27272a',
        inputBackground: '#09090b',
        ring: '#d4d4d8',
        radius: 12,
        chart1: '#e76e50',
        chart2: '#2a9d8f',
        chart3: '#2a6f97',
        chart4: '#e9c46a',
        chart5: '#f4a261',
    }
};

// Revert to Light Mode default as standard
export const currentTheme = theme.light; 
